#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 20, 2020 11:42:47 AM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global nomesDeviceBluetooth
    nomesDeviceBluetooth = tk.StringVar()
    global enderecoCamera
    enderecoCamera = tk.StringVar()
    global distRealX
    distRealX = tk.StringVar()
    global distRealY
    distRealY = tk.StringVar()
    global k1
    k1 = tk.StringVar()
    global k2
    k2 = tk.StringVar()
    global k3
    k3 = tk.StringVar()
    global k4
    k4 = tk.StringVar()
    global kpgui
    kpgui = tk.StringVar()
    global kigui
    kigui = tk.StringVar()
    global cbHabMotoresValue
    cbHabMotoresValue = tk.IntVar()
    global cbPosVelLQR
    cbPosVelLQR = tk.IntVar()
    global cbPosVelGuinada
    cbPosVelGuinada = tk.IntVar()
    global cbControleGuinadaValue
    cbControleGuinadaValue = tk.IntVar()
    global varRefDist
    varRefDist = tk.StringVar()
    global cbHabilitaRastrear
    cbHabilitaRastrear = tk.IntVar()
    global cbObjectT_Dist
    cbObjectT_Dist = tk.IntVar()
    global varKg
    varKg = tk.StringVar()
    global cbObjectHabCam
    cbObjectHabCam = tk.IntVar()
    global cbObjectHabLidar
    cbObjectHabLidar = tk.IntVar()

def cliqueCanvas(p1):
    print('tela1_1_support.cliqueCanvas')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import tela1_1
    tela1_1.vp_start_gui()




